### ISSUE TITLE
Error: Cannot find module 'C:\projects\myProject\extension/manifest.json'

### ISSUE THREAD

**Issue by Nantris** [dimitarnestorov/react-devtools-electron#183]
> 16:55:51.233 > Error: Cannot find module 'C:\projects\myProject\extension/manifest.json'
    at webpackEmptyContext (webpack:///./node_modules/react-devtools-electron/dist_sync_^.*\/manifest\.json$?:2:10)
    at eval (webpack:///./node_modules/react-devtools-electron/dist/utils.js?:6:129)
    at Object.call (C:\projects\myProject\app\/main.dev.build.js:19125:1)
    at __webpack_require__ (C:\projects\myProject\app\/main.dev.build.js:21:30)
    at eval (webpack:///./node_modules/react-devtools-electron/dist/index.js?:4:15)

Using `Electron@8.2.x`

**Comment by SaiKDot** [comment]
Facing the same issue with `Electron@10.2.0`

**Comment by hafizglasswall** [comment]
+1
